In [2]:
import pandas as  pd
import numpy as np
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

In [3]:
matches_df = pd.read_csv('F:\CODING\ipl project\drive-download-20260415T150344Z-3-001\ipl_matches_data.csv')

In [4]:
matches_df.head()

,match_id,season_id,balls_per_over,city,match_date,event_name,match_number,gender,match_type,format,overs,season,team_type,venue,toss_winner,team1,team2,toss_decision,match_winner,win_by_runs,win_by_wickets,player_of_match,result,stage
0,335982,2008,6,Bangalore,18-04-2008,Indian Premier League,1.0,male,T20,T20,20,2008,club,M Chinnaswamy Stadium,Royal Challengers Bangalore,Royal Challengers Bangalore,Kolkata Knight Riders,field,Kolkata Knight Riders,140.0,NaN,46.0,win,NaN
1,335983,2008,6,Chandigarh,19-04-2008,Indian Premier League,2.0,male,T20,T20,20,2008,club,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,Punjab Kings,Chennai Super Kings,bat,Chennai Super Kings,33.0,NaN,11943.0,win,NaN
2,335984,2008,6,Delhi,19-04-2008,Indian Premier League,3.0,male,T20,T20,20,2008,club,Feroz Shah Kotla,Rajasthan Royals,Delhi Capitals,Rajasthan Royals,bat,Delhi Capitals,NaN,9.0,11982.0,win,NaN
3,335985,2008,6,Mumbai,20-04-2008,Indian Premier League,5.0,male,T20,T20,20,2008,club,Wankhede Stadium,Mumbai Indians,Mumbai Indians,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,NaN,5.0,11935.0,win,NaN
4,335986,2008,6,Kolkata,20-04-2008,Indian Premier League,4.0,male,T20,T20,20,2008,club,Eden Gardens,Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders,NaN,5.0,11922.0,win,NaN

In [5]:
matches_df = matches_df.drop(columns=[
    'balls_per_over', 'match_date','city', 'event_name', 'gender',
    'match_number', 'match_type', 'format', 'overs',
    'team_type', 'result', 'win_by_runs', 'win_by_wickets',
    'player_of_match', 'stage'
])

In [14]:
matches_df.head()

,match_id,season_num,season,venue,toss_winner,team1,team2,toss_decision,match_winner,toss_won_match
0,335982,2008,2008,M Chinnaswamy Stadium,Royal Challengers Bangalore,Royal Challengers Bangalore,Kolkata Knight Riders,field,Kolkata Knight Riders,0
1,335983,2008,2008,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,Punjab Kings,Chennai Super Kings,bat,Chennai Super Kings,1
2,335984,2008,2008,Feroz Shah Kotla,Rajasthan Royals,Delhi Capitals,Rajasthan Royals,bat,Delhi Capitals,0
3,335985,2008,2008,Wankhede Stadium,Mumbai Indians,Mumbai Indians,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,0
4,335986,2008,2008,Eden Gardens,Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders,0

In [7]:
matches_df['toss_won_match'] = (matches_df['toss_winner'] == matches_df['match_winner']).astype(int)

In [8]:
matches_df.rename(columns={'season_id': 'season_num'}, inplace=True)

In [13]:
print(matches_df.isnull().sum())

match_id          0
season_num        0
season            0
venue             0
toss_winner       0
team1             0
team2             0
toss_decision     0
match_winner      0
toss_won_match    0
dtype: int64

In [12]:
matches_df[matches_df.isnull().any(axis=1)]

Empty DataFrame
Columns: [match_id, season_num, season, venue, toss_winner, team1, team2, toss_decision, match_winner, toss_won_match]
Index: []

In [11]:
matches_df = matches_df.dropna(subset=["match_winner"])

In [21]:
matches_df.to_csv('matches_clean.csv',index=False)

In [16]:
print(matches_df.isnull().sum())

match_id          0
season_num        0
season            0
venue             0
toss_winner       0
team1             0
team2             0
toss_decision     0
match_winner      0
toss_won_match    0
dtype: int64

In [17]:
# If toss winner chose bat — did they win?
matches_df['bat_first_won'] = (
    (matches_df['toss_decision'] == 'bat') & 
    (matches_df['toss_winner'] == matches_df['match_winner'])
).astype(int)

# If toss winner chose field — did they win?
matches_df['field_first_won'] = (
    (matches_df['toss_decision'] == 'field') & 
    (matches_df['toss_winner'] == matches_df['match_winner'])
).astype(int)

In [18]:
matches_df.head()

,match_id,season_num,season,venue,toss_winner,team1,team2,toss_decision,match_winner,toss_won_match,bat_first_won,field_first_won
0,335982,2008,2008,M Chinnaswamy Stadium,Royal Challengers Bangalore,Royal Challengers Bangalore,Kolkata Knight Riders,field,Kolkata Knight Riders,0,0,0
1,335983,2008,2008,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,Punjab Kings,Chennai Super Kings,bat,Chennai Super Kings,1,1,0
2,335984,2008,2008,Feroz Shah Kotla,Rajasthan Royals,Delhi Capitals,Rajasthan Royals,bat,Delhi Capitals,0,0,0
3,335985,2008,2008,Wankhede Stadium,Mumbai Indians,Mumbai Indians,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,0,0,0
4,335986,2008,2008,Eden Gardens,Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders,0,0,0

In [20]:
matches_df['season'] = matches_df['season'].str.replace('2020/21', '2020')